apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nodejs-app
    app.kubernetes.io/instance: nodejs-app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: nodejs-app
spec:
  selector:
    app: nodejs-app
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000
